export const ARTICLE_ACTION_CONSTRANTS = {
  ARTICLE_GET_ALL_ARTICLES: 'ARTICLE_GET_ALL_ARTICLES',
  ARTICLE_GET_SINGLE_ARTICLE: 'ARTICLE_GET_SINGLE_ARTICLE',
  ARTICLE_ADD_SINGLE_ARTICLE: 'ARTICLE_ADD_SINGLE_ARTICLE',
  ARTICLE_UPDATE_SINGLE_ARTICLE: 'ARTICLE_UPDATE_SINGLE_ARTICLE',
  ARTICLE_DELETE_SINGLE_ARTICLE: 'ARTICLE_DELETE_SINGLE_ARTICLE',
  ARTICLE_ADD_MULTTIPLE_ARTICLES: 'ARTICLE_ADD_MULTTIPLE_ARTICLES',
};

export default ARTICLE_ACTION_CONSTRANTS;
